TP_Adivinator/TP_Adivinator/Models/Game.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TP_Adivinator.Models
{
    public class Game
    {

        public Dictionary<string, Player> players = new Dictionary<string, Player>();
        private static Game game;


        static public Game GetGame()
        {
            if (game == null)
            {
                game = new Game();
            }
            return game;
        }

        public Player GetPlayer(string name)
        {
            Player player;
            if (!players.ContainsKey(name))
            {
                player = new Player(name);
                players.Add(name, player);
            }
            else
            {
                player = players[name];
            }

            return player;
        }

        public Match StartGame(String name)
        {
            return (StartGame(GetPlayer(name)));
        }

        public Match StartGame(Player player)
        {
            return new Match(player);
        }

        public void AddRecord(Match match)
        {
            try
            {
                players.Add(match.player.Name, match.player);
            }
            catch (ArgumentException)
            {
                string name = match.player.Name;
                // Player player = players.Values(name); obtener jug en lista
                players.Remove(name);
            }


        }
    }



}

TP_Adivinator/TP_Adivinator/Models/Match.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TP_Adivinator.Models
{
    public class Match
    {
        public Player player;
        private int randomNumber;
        private readonly int maxAttempts = 10;
        public List<int> attempts = new List<int>();
        public bool Won { get; set; }

        public Match(Player player)
        {
            this.player = player;
        }


        public void SetRandom () 
        {
            Random r = new Random();
            randomNumber = r.Next(minValue: 1, maxValue: 100);
        }

        public void SetWin(Match match) 
        {
            player.AddWin(match);
            Won = true;
        }

        public int GetAttempts()
        {
            return maxAttempts - this.attempts.Count();
        }
        public bool Validate(int numberOfUser) 
        {
            if(numberOfUser > 0 && numberOfUser < 101)
            {
                return true;
            }
            return false;
        }


        public int Play (int numberOfUser) 
        {
            if( Validate(numberOfUser))
            {
                Won = numberOfUser == this.randomNumber;
                if (!Won)
                {
                    this.attempts.Add(Convert.ToInt32(numberOfUser));
                }
            }
            return numberOfUser - this.randomNumber;
        }
    }
}

TP_Adivinator/TP_Adivinator/Models/Player.cs
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Web;

    namespace TP_Adivinator.Models
    {
        public class Player
        {
            
            public string Name { get; set; }


            public List<Match> wonMatches = new List<Match>();

            public Player(string name)
            {
                this.Name = name;
            }
           

            public void AddWin(Match match) 
            {
                wonMatches.Add(match);
            }
        }   
    }

TP_Adivinator/TP_Adivinator/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using TP_Adivinator.Filters;
using TP_Adivinator.Models;

namespace TP_Adivinator.Controllers
{
    public class GameController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            if(Session["Player"] != null)
            {
                return RedirectToAction("MatchLoad");
            }

            return View();
        }

        [HttpPost]
        public ActionResult Login(string name) 
        {
            var game = Game.GetGame();
            var player = game.GetPlayer(name);
            Session["Player"] = player;
            var wonMatches = 0;
            Session["WonMatches"] = wonMatches;
            return RedirectToAction("MatchLoad");

        }
        [UserFilter]
        public ActionResult MatchLoad()
        {
            Player player = (Player)Session["Player"];
            Match match = new Match(player);
            match.SetRandom();
            HttpCookie wonMatchesNav = Request.Cookies["wonMatchesNav"];
            if (wonMatchesNav != null)
            {
                var WonMatchesNave = wonMatchesNav["NavRecord"].ToString();
                Session["NavRecord"] = Convert.ToInt32(WonMatchesNave);
            }
            else
            {
                int navRecord = 0;

                Session["NavRecord"] = navRecord;
            }
            Session["Match"] = match;
            return View("Play", match);
        }

        [UserFilter]
        public ActionResult Play()
        {
            Match match = (Match)Session["Match"];
            int numberOfPlayer = Convert.ToInt16(Request.Form["number"]);
            if (numberOfPlayer < 101 && numberOfPlayer > 0)
            {
                int result = match.Play(numberOfPlayer);
                if (result == 0)
                {
                    match.SetWin(match);
                    var wonMatches = (int)Session["WonMatches"];
                    wonMatches++;
                    Session["WonMatches"] = wonMatches;
                    ViewBag.Result = "¡Ganaste!";
                }
                if (result > 0)
                {
                    ViewBag.Result = "¡Numero mas bajo!";
                }
                if (result < 0)
                {
                    ViewBag.Result = "¡Numero mas alto!";
                }
                if (match.GetAttempts() == 0)
                {
                    ViewBag.Result = "¡Perdiste!";

                }
            }
            else
            {
                ViewBag.Result = "¡Numero fuera de rango!";
            }
            
            return View(match);
        }

        public ActionResult Ranking()
        {
            var game = Game.GetGame();
            string bestPlayer = null;
            var bestScore = 0;
            foreach (KeyValuePair<string, Player> player in game.players)
            {
                if(player.Value.wonMatches.Count() > bestScore)
                {
                    bestScore = player.Value.wonMatches.Count();
                    bestPlayer = player.Key;
                }
            }
            ViewBag.bestScore = bestScore;
            ViewBag.bestPlayer = bestPlayer;
            return View();
        }

        [UserFilter]
        [HttpGet]
        public ActionResult LogOut()
        {
            int navRecord = (int)Session["NavRecord"];
            int wonMatches = (int)Session["WonMatches"];
            if (wonMatches >  navRecord)
            {

                navRecord = wonMatches;
                
            }
            HttpCookie wonMatchesNav = new HttpCookie("wonMatchesNav");
            wonMatchesNav["NavRecord"] = Convert.ToString(navRecord);
            wonMatchesNav.Expires = new DateTime(2020, 12, 25);
            Response.Cookies.Add(wonMatchesNav);

            Session.Abandon();
            return View("Index");
        }
    }

}

TP_Adivinator/TP_Adivinator/Views/Game/Index.cshtml
<div>
    <h1>Bienvenido a Adivinator</h1>
</div>

<div class="container">
    <form method="post" name="LoginForm" id="LoginForm" action='@Url.Action("Login","Game")'>
        <div>
            <br />
            <label for="Name">Nombre</label>
            <input type="text" required class="form-control" name="Name" id="Name" placeholder="Ingresa tu nombre" runat="server">
        </div>
        <div>
            <br />
            <input type="submit" class="btn btn-warning" name="play" />
        </div>

    </form>


</div>
<body style = "background-image:url(/Images/adivino.jpg); background-repeat:no-repeat; background-position: center"></body>

TP_Adivinator/TP_Adivinator/Views/Game/Play.cshtml
@model TP_Adivinator.Models.Match
@using TP_Adivinator.Models;

<div align="right">
    <a class="btn btn-danger" href='@Url.Action("LogOut", "Game")' role="button">Log Out</a>
</div>


<div>
    <h3>Jugador: @Model.player.Name</h3>

    <h4>Elegi un número entre 1 y 100</h4>
</div>
<div>
    <label for="attempts">Intentos restantes: @Model.GetAttempts()</label>
</div>



<div class="container">
    <form method="post" action='@Url.Action("Play")'>
        @if ((Model.GetAttempts()) > 0 && @Model.Won != true)
        {
            <input type="number" required name="number" id="number" />
            <asp:RangeValidator ID="RangeValidator1" runat="server" ControlToValidate="number"
                                ErrorMessage="Enter value in specified range" ForeColor="Red" MaximumValue="199" MinimumValue="101"
                                SetFocusOnError="True" Type=" Integer"></asp:RangeValidator>
            <br />

            <input type="submit" class="btn btn-primary" name="buttonrUser" id="buttonUser" />
            <br />
        }
        <label for="result">@ViewBag.Result</label>
    </form>
</div>


    @if (@Model.Won != true)
    {
        <body style = "background-image:url(/Images/thinking.jpg)"></body>
        
    }

    @if (@Model.Won != false)
    {
        <body style = "background-image:url(/Images/won.png); background-repeat:no-repeat; background-position: center"></body>
        
    }


<div>
    <h5>Partidas ganadas en esta sesion: @Session["WonMatches"]</h5>
    <h5>Record en este navegador: @Session["NavRecord"]</h5>
</div>

<div>

    <h4>Numeros jugados :</h4>
    <ul class="list-inline">
        @foreach (var attempt in (Model.attempts))
        {
            <li class="list-inline-item">@attempt</li>
        }
    </ul>
</div>

<div>
   
        <input type="button" class="btn btn-primary" value="Volver a jugar" onclick="location.href='@Url.Action("MatchLoad", "Game")'" />
</div>

<div align="right">
    <input type="button" class="btn btn-warning" value="Ranking" onclick="location.href='@Url.Action("Ranking", "Game")'" />
</div>

TP_Adivinator/TP_Adivinator/Views/Game/Ranking.cshtml
<h2>Ranking</h2>

<div class="container">
    <div>
        <table class="table table-striped">
            <tr>
                <th>Nombre</th>
                <th>Partidas Ganadas</th>

            </tr>
            
            
            <tr>
                <td>@ViewBag.bestPlayer</td>

                <td>@ViewBag.bestScore</td>
                

            </tr>
           
        </table>
    </div>
</div>

TP_Adivinator/TP_Adivinator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Adivinator</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
        <div class="container" align ="left">
            <img src="/Images/logo.png" alt="logo" height="65" width="240" />
        </div>
            
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Adivinator</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>